### ISSUE TITLE
English comments ?

### ISSUE THREAD

**Issue by Aggebitter** [danidask/MatrizLed#1]
Looking for a MAX7219 HW SPI lib to run on ESP32 arduino.

**Comment by danidask** [comment]
Hi  Aggebitter,
I made this for an Arduino course here in Spain, so I commented and named the methods in Spanish in order to be more beginner friendly for the students. 
It also works with the ESP32. I have no plans to translate it, but feel free to fork it and translate it yourself, it wont be hard.
